INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('jimin', '1234', 'test', 'test@naver.com');
INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('test2', '1234', 'test2', 'test2@naver.com');

INSERT INTO QUESTION (WRITER, TITLE, CONTENTS) VALUES ('JAVAMAN','TEST','TEST 글입니다.');
INSERT INTO QUESTION (WRITER, TITLE, CONTENTS) VALUES ('JAVACHILD','TEST2','TEST 글입니다.');